version: "3.1"

services: 
     department:
        image: charantej224/deptimage:1
        ports:
          - "8093:8093"
        deploy:
            replicas: 4
            placement:
               constraints: 
                   - node.role==worker
